version: '3'
services:
  web:
    build:
      context: .
      args:
        - host_user_name=${host_user_name}
        - host_group_name=${host_group_name}
        - host_uid=${host_uid}
        - host_gid=${host_gid}
    command: mix phx.server
    environment:
      DB_HOST: db
    links:
      - db
    ports:
      - 4000:4000
    volumes:
      - .:/work
    working_dir: /work
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata:
